Story5/urls.py
from django.conf.urls import url
from django.urls import path
from .views import profile, home, schedule, addschedule, clearschedule

urlpatterns = [
    path('profile', profile, name='Profile'),
    path('', home, name='Home'),
    path('home', home, name='Home'),
    path('schedule', schedule, name='Schedule'),
    path('addschedule', addschedule, name='addschedule'), # for form submission
    path('clearschedule', clearschedule, name='clearschedule') # for schedule clear
]

Story5Project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('Story5.urls', 'Story5'), namespace='Story5')),
]

Story5/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date

# Create your models here.  
class Activity(models.Model):
    # author = models.ForeignKey(Person, on_delete = models.CASCADE)
    name = models.CharField(max_length=80)
    category = models.CharField(max_length=50)
    location = models.CharField(max_length=100)
    date = models.DateField(default=timezone.now)
    time = models.TimeField()

Story5/forms.py
from django import forms

class Message_Form(forms.Form):
    
    error_messages = {
        'required': 'Please fill this input',
    }
    
    name_attrs = {
        'class': 'form-control form-group',
        'placeholder': 'Enter name of activity'
    }

    cat_attrs = {
        'class': 'form-control form-group',
        'placeholder': 'Enter category of activity'
    }

    loc_attrs = {
        'class': 'form-control form-group',
        'placeholder': 'Enter location of activity'
    }

    date_attrs = {
        'class': 'form-control form-group',
        'placeholder': 'Enter date of activity',
        'type': 'date'
    }

    time_attrs = {
        'class': 'form-control form-group',
        'placeholder': 'Enter time of activity',
        'type': 'time'
    }

    name = forms.CharField(label='Activity Name', required=True, max_length=80, widget=forms.TextInput(attrs=name_attrs))
    category = forms.CharField(label='Category', required=True,max_length=50, widget=forms.TextInput(attrs=cat_attrs))
    location = forms.CharField(label='Location', required=False,max_length=100, widget=forms.TextInput(attrs=loc_attrs))
    date = forms.DateField(label='Date', required=True, widget=forms.DateInput(attrs=date_attrs))
    time = forms.TimeField(label='Time', required=True, widget=forms.TimeInput(attrs=time_attrs))

Story5/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .forms import Message_Form
from .models import Activity

# Create your views here.

response = {}

def profile(request):
    return render(request,'Profile.html')


def home(request):
    return render(request,'Home.html')


def schedule(request):
    response['title'] = 'Add Schedule'
    response['message_form'] = Message_Form
    response['activities'] = Activity.objects.all().values()
    return render(request,'Schedule.html', response)


def addschedule(request):
    # create a form instance and populate it with data from the request:
    form = Message_Form(request.POST or None)

    # check whether method is a POST and whether the form is valid
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['category'] = request.POST['category']
        response['location'] = request.POST['location']
        response['date'] = request.POST['date']
        response['time'] = request.POST['time']
        activity = Activity(name=response['name'], category=response['category'], location=response['location'], date=response['date'], time=response['time'])
        activity.save()
        return HttpResponseRedirect('schedule')

    # if method is a GET (or any other method) or form is invalid, create a blank form
    else:
        return HttpResponseRedirect('schedule')


def clearschedule(request):
    for i in Activity.objects.all():
        i.delete()
    return HttpResponseRedirect('schedule')

Story5/templates/Home.html
<!DOCTYPE html>
<html>
{% load static %}
    <head>
        <title>PPWLab - My Home</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=yes">

    	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'Lab3.css' %}">
    	<style type="text/css">
            /** {
                border-style: solid;
            }*/

            #profilePhoto {
                display: block;
                margin-left: auto;
                margin-right: auto;
            }

            #mainID {
                text-align: center;
            }

            #card3 {
                margin: 2rem 2rem 2rem 2rem;
            }
    	</style>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </head>

    <body>
    	<!-- from bootstrap -->
    	<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="navBar">
            <img class="rounded-circle" id="kakPeweLogo" src="{% static 'img/Kak-Pewe.jpg' %}">
		    <a class="navbar-brand" id="navBarBrand" href="#"><h3>PPWLAB - MY HOME</h3></a>

		    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
		        <span class="navbar-toggler-icon"></span>
		    </button>

		    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
			    <div class="navbar-nav" id="navBarNav">
			    	<a class="nav-item nav-link active" href="#"><h3>Home <span class="sr-only">(current)</span></h3></a>
                    <a class="nav-item nav-link" href="schedule"><h3>Schedule</h3></a>
			        <a class="nav-item nav-link" href="profile"><h3>Profile</h3></a>
			        <a class="nav-item nav-link" href="profile"><img class="rounded-circle" id="profileLogo" src="{% static 'img/Foto.jpg' %}"></a>
			    </div>
		    </div>
		</nav>

        <!-- main card -->
        <div class="card" id="card1">
            <div class="card-body">
                <div class="card-1-home">
                    <img src="{% static 'img/Foto.jpg' %}" class="img-thumbnail rounded-circle" id="profilePhoto" alt="Picture of Kevin Christian Chandra">
                </div>

                <br>

                <div class="card-1-home" id="mainID">
                    <h2 id="name">KEVIN CHRISTIAN CHANDRA</h2>
                    <hr style="width: 70%">
                    <h2 id="career">"Do your best in everything you do."</h2>
                </div>
            </div>
        </div>

        <!-- About -->
        <div id="card2">
    		<div class="card header-card">
                <div class="card-body header-card-body">
                    <h4 id="about">About</h4>
                </div>
            </div>

            <div class="card">
                <div class="card-body">
                    <p>Welcome to my website! I created this website to fullfil the Web Designing task given by my Teacher. This website was intended to only display my profile, but then I decided to make a home page which shows some articles I would like to post. The main content of this website is my personal profile and things I like or am interested in. I do hope you enjoy scrolling though this experimental website.</p>
                </div>
            </div>
        </div>

        <!-- Article -->
        <div id="card3">
            <div class="card header-card">
                <div class="card-body header-card-body">
                    <h4 id="article">Today's Articles</h4>
                </div>
            </div>

            <div class="card">
                <div class="card-body">
                    <h2>Giant Panda</h2>
                    <p style="font-style: italic; font-size: 0.7rem">from Wikipedia</p>
                    <hr>
                    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Panda_Cub_from_Wolong%2C_Sichuan%2C_China.JPG/330px-Panda_Cub_from_Wolong%2C_Sichuan%2C_China.JPG" class="img-thumbnail" alt="A seven months-old Giant Panda">

                    <p>The giant panda (Ailuropoda melanoleuca, literally "black and white cat-foot"; Chinese: 大熊猫; pinyin: dà xióng māo, literally "big bear cat"), also known as panda bear or simply panda, is a bear native to south central China. It is easily recognized by the large, distinctive black patches around its eyes, over the ears, and across its round body. The name "giant panda" is sometimes used to distinguish it from the unrelated red panda. Though it belongs to the order Carnivora, the giant panda's diet is over 99% bamboo. Giant pandas in the wild will occasionally eat other grasses, wild tubers, or even meat in the form of birds, rodents, or carrion. In captivity, they may receive honey, eggs, fish, yams, shrub leaves, oranges, or bananas along with specially prepared food.</p>

                    <p>The giant panda lives in a few mountain ranges in central China, mainly in Sichuan, but also in neighbouring Shaanxi and Gansu. As a result of farming, deforestation, and other development, the giant panda has been driven out of the lowland areas where it once lived.</p>

                    <p><a href="https://en.wikipedia.org/wiki/Giant_panda" target="_blank">(Click here to read more...)</a></p>
                </div>

                <div class="card-body">
                    <h2>Bootstrap</h2>
                    <p style="font-style: italic; font-size: 0.7rem">from Wikipedia</p>
                    <hr>
                    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Boostrap_logo.svg/330px-Boostrap_logo.svg.png" class="img-thumbnail" alt="Bootstrap Logo">
                    
                    <p>Bootstrap is a free and open-source front-end framework for designing websites and web applications. It contains HTML- and CSS-based design templates for typography, forms, buttons, navigation and other interface components, as well as optional JavaScript extensions. Unlike many earlier web frameworks, it concerns itself with front-end development only.</p>

                    <p>Bootstrap is modular and consists of a series of Less stylesheets that implement the various components of the toolkit. These stylesheets are generally compiled into a bundle and included in web pages, but individual components can be included or removed. Bootstrap provides a number of configuration variables that control things such as color and padding of various components.</p>

                    <p><a href="https://en.wikipedia.org/wiki/Bootstrap_(front-end_framework)" target="_blank">(Click here to read more...)</a></p>
                </div>
            </div>
        </div>
    </body>
</html>

Story5/templates/Profile.html
<!DOCTYPE html>
<html>
{% load static %}
    <head>
        <title>PPWLab - My Profile</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=yes">

    	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'Lab3.css' %}">
    	<style type="text/css">
            /** {
                border-style: solid;
            }*/

            #mainID {
                position: absolute;
                margin-left: 3rem;
                top: 30px;
                width: 65%;
            }

            #lowerCard1, #upperCard1 {
                display: block;
            }

            .card-1-biodata {
                display: inline-block;
            }

            .bio-icon {
                max-height: 1rem;
                max-width: 1rem;
                display: block;
                margin-top: 1.45rem;
                margin-right: 1rem;
                margin-left: 1rem;
            }

            #bioCategories {
                min-width: 10rem;
                font-weight: bold;
            }
    	</style>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </head>

    <body>
    	<!-- from bootstrap -->
    	<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="navBar">
            <img class="rounded-circle" id="kakPeweLogo" src="{% static 'img/Kak-Pewe.jpg' %}">
		    <a class="navbar-brand" id="navBarBrand" href="#"><h3>PPWLAB - MY PROFILE</h3></a>
		    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
		        <span class="navbar-toggler-icon"></span>
		    </button>
		    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
			    <div class="navbar-nav" id="navBarNav">
			    	<a class="nav-item nav-link" href="home"><h3>Home</h3></a>
                    <a class="nav-item nav-link" href="schedule"><h3>Schedule</h3></a>
			        <a class="nav-item nav-link active" href="#"><h3>Profile <span class="sr-only">(current)</span></h3></a>
			        <a class="nav-item nav-link" href="#"><img class="rounded-circle" id="profileLogo" src="{% static 'img/Foto.jpg' %}"></a>
			    </div>
		    </div>
		</nav>

		
        <div class="card" id="card1">
            <div class="card-body">

                <div id="upperCard1">
                    <div class="card-1-biodata">
                        <img src="{% static 'img/Foto.jpg' %}" class="img-thumbnail rounded-circle" id="profilePhoto" alt="Picture of Kevin Christian Chandra">
                    </div>

                    <div class="card-1-biodata" id="mainID">
                        <h1 id="name">KEVIN CHRISTIAN CHANDRA</h1>
                        <hr>
                        <h5 id="career">Student at University of Indonesia</h5>
                    </div>
                </div>

                <div id="lowerCard1">
                    <div class="card-1-biodata" id="bioIcons">
                        <img src="{% static 'img/Birthday-icon.png' %}" class="bio-icon">
                        <img src="{% static 'img/Address.png' %}" class="bio-icon">
                        <img src="{% static 'img/Phone 2.png' %}" class="bio-icon">
                        <img src="{% static 'img/Mail.png' %}" class="bio-icon">
                        <img src="{% static 'img/Hobby.png' %}" class="bio-icon">
                        <img src="{% static 'img/Speaker.png' %}" class="bio-icon">
                    </div>

                    <div class="card-1-biodata" id="bioCategories">
                        <p class="bio-category">Birth</p>
                        <p class="bio-category">Address</p>
                        <p class="bio-category">Phone</p>
                        <p class="bio-category">E-Mail</p>
                        <p class="bio-category">Hobby</p>
                        <p class="bio-category">Motto</p>
                    </div>

                    <div class="card-1-biodata" id="bioContents">
                        <p class="bio-content">Jakarta, September 27, 1999</p>
                        <p class="bio-content">Jl. Tanah Sereal XVI, No. 5, Jakarta Barat, DKI Jakarta</p>
                        <p class="bio-content">081295239229</p>
                        <p class="bio-content">kevinc.27999@gmail.com</p>
                        <p class="bio-content">Reading, watching movies, playing video games</p>
                        <p class="bio-content">"Do your best in everything you do."</p>
                    </div>
                </div>

            </div>
        </div>

        <!-- My Description -->
        <div id="card2">
    		<div class="card header-card">
                <div class="card-body header-card-body">
                    <h4 id="description">Description</h4>
                </div>
            </div>

            <div class="card">
                <div class="card-body">
                    <p>I am a student at University of Indonesia's Faculty of Computer Science. I first enrolled here at July 2017. I am now on my second year. I'm currently a teaching assistant for the Fundamental Programming 1 Class. I also join the commitee of RKF 2018 and PMB 2018, events on my campus. I live by my motto, that I should strive to do the best in my study, not just to get the best score. Score is just a number, but experience and skills are more than that number. And I believe that with good skills, that number will then come along.</p>
                </div>
            </div>
        </div>

        <div class="card-columns content-cards">
            <div class="card card-combi" id="card3">
                <div class="card header-card">
                    <div class="card-body header-card-body">
                        <h4 id="exp">Experience</h4>
                    </div>
                </div>

                <div class="card">
                    <div class="card-body list-card">
                        <ul>2018 - Teaching assistant for the Fundamental Programming 1 Class</ul>
                        <ul>2018 - Mentor for PMB Fasilkom UI 2018</ul>
                        <ul>2017 - Intern at Sekolah BEM Fasilkom UI</ul>
                    </div>
                </div>
            </div>

            <div class="card card-combi" id="card4">
                <div class="card header-card">
                    <div class="card-body header-card-body">
                        <h4 id="achievements">Achievements</h4>
                    </div>
                </div>

                <div class="card">
                    <div class="card-body list-card">
                        <ul>2016 - 2nd Place in the FLS2N Jakarta Pusat on Poster Design</ul>
                        <ul>2016 - 3rd Place in the OSK Astronomi Jakarta Pusat 1</ul>
                        <ul>2015 - 1st Place in the OSK Astronomi Jakarta Pusat 1</ul>
                    </div>
                </div>
            </div>

            <div class="card card-combi" id="card5">
                <div class="card header-card">
                    <div class="card-body header-card-body">
                        <h4 id="education">Education</h4>
                    </div>
                </div>

                <div class="card">
                    <div class="card-body list-card">
                        <ul>2017 - Now</ul>
                        <ul>University of Indonesia's Faculty of Computer Science</ul>
                        <ul>2014 - 2017</ul>
                        <ul>Kristen Ketapang 1 Senior High School Jakarta</ul>
                        <ul>2011 - 2014</ul>
                        <ul>Kristen Ketapang 1 Junior High School Jakarta</ul>
                        <ul>2005 - 2011</ul>
                        <ul>Kristen Ketapang 1 Elementary School Jakarta</ul>
                    </div>
                </div>
            </div>
        </div>

    </body>
</html>

Story5/templates/Schedule.html
<!DOCTYPE html>
<html>
{% load static %}
    <head>
        <title>PPWLab - My Schedule</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=yes">

    	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'Lab3.css' %}">
    	<style type="text/css">
            /** {
                border-style: solid;
            }*/
    	</style>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </head>

    <body>
    	<!-- from bootstrap -->
    	<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="navBar">
            <img class="rounded-circle" id="kakPeweLogo" src="{% static 'img/Kak-Pewe.jpg' %}">
            <a class="navbar-brand" id="navBarBrand" href="#"><h3>PPWLAB - MY SCHEDULE</h3></a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav" id="navBarNav">
                    <a class="nav-item nav-link" href="home"><h3>Home</h3></a>
                    <a class="nav-item nav-link active" href="#"><h3>Schedule <span class="sr-only">(current)</span></h3></a>
                    <a class="nav-item nav-link" href="profile"><h3>Profile</h3></a>
                    <a class="nav-item nav-link" href="profile"><img class="rounded-circle" id="profileLogo" src="{% static 'img/Foto.jpg' %}"></a>
                </div>
            </div>
        </nav>

        <!-- main card -->
        <div class="card" id="card1">
            <div class="card-body">
                <div>
                    <h2 id="name">Add a New Activity</h2>
                    <hr>
                </div>

                <form method="POST" action="{% url 'Story5:addschedule' %}">
                    {% csrf_token%}
                    {{message_form}}

                    <button type="submit" class="btn btn-success">Submit</button>
                </form>
            </div>
        </div>

        <div id="card2">
    		<div class="card header-card">
                <div class="card-body header-card-body">
                    <h4 id="about">My Activities</h4>
                </div>
            </div>

            <div class="card">
                <div class="card-body">
                    <table class="table table-hover" id="scheduleTable">
                        <thead>
                            <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Category</th>
                            <th scope="col">Location</th>
                            <th scope="col">Date</th>
                            <th scope="col">Time</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for Activity in activities %}
                            <tr>
                            <td scope="row">{{Activity.name}}</td>
                            <td>{{Activity.category}}</td>
                            <td>{{Activity.location}}</td>
                            <td>{{Activity.date}}</td>
                            <td>{{Activity.time}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                    <form method="POST" action="{% url 'Story5:clearschedule' %}">
                        {% csrf_token%}
                        <button type="submit" class="btn btn-danger">Clear Schedule</button>
                    </form>
                </div>
            </div>

        </div>
    </body>
</html>